model:
  arch: mini_gpt4
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 160
  end_sym: "###"
  low_resource: True
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: './pretrained/minigpt4/prerained_minigpt4_7b.pth'

  # ViT-encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"

  # Q-Former
  num_query_token: 32

  # Vicuna
  llama_model: "./pretrained/vicuna_working_weights/vicuna-7b-v0/"
